### ISSUE TITLE
有点蚌埠住2333333

### ISSUE THREAD

**Issue by qazmko1029** [yqorvgb/ChinesePad#1]
知乎某个大喊抵制notepad++的帖子来的。这种repo第二次出现了啊，notepad++替换个软件名称，加个love china的标语，换个logo就是爱国的ChinesePad了……说实话有点脱裤子放屁的感觉，蚌埠住😅
不是说就不能这么搞，反正是GPL想怎么改怎么改，但这种分支repo的问题在于，本质还是人家的软件，所有更新都得跟在人屁股后面，除非自己有能力单独维护或者干脆不更新。
先不说repo主有没有能力，这连修改的源码都没放出来，实在是不太敢用。还有Logo审美真的不到位，国旗当Logo不是不行但也不是用成这样的，好歹弄个旗子飘扬的感觉呢……
以上。

**Comment by yqorvgb** [comment]
关于第一点，每个人有不同的看法，你说脱裤子放屁，那就脱裤子放屁，我不做评价
关于第二点，更新问题，我没有精力也没有能力维护，所以不更新
关于第三点，关于源码，贴源码完全没问题，你这种质疑是对的，我考虑不周
关于第四点，关于logo，你觉得不好看请提供好看的logo，或者自己去编译

**Comment by yqorvgb** [comment]
@qazmko1029
